### ISSUE TITLE
Registry offline?

### ISSUE THREAD

**Issue by Jason2866** [platformio/platformio-registry#1]
@ivankravets We get this error in our CI and build gitub action workflows.
```
Platform Manager: Installing espressif8266 @ 2.6.3
Error: Could not install package 'espressif8266 @ 2.6.3' for 'linux_x86_64' system
Error: Process completed with exit code 1.
```

Sorry if this is the wrong github for submitting the issue

**Comment by ivankravets** [comment]
Sorry, it was our bug, and we quickly fixed it. Do you still experience this issue?

**Comment by Jason2866** [comment]
Thx, it does work now.

**Comment by ivankravets** [comment]
Thanks for the report!
