### ISSUE TITLE
My attempt to unpublish and re-publish package broke publishing

### ISSUE THREAD

**Issue by leon0399** [platformio/platformio-registry#103]
My steps:

1. I published a few versions of `leon0399/Serial_BLE`.
2. I decided that I want it to be under another namespace
3. I unpublish all versions of `leon0399/Serial_BLE`.
4. I update my account username from `leon0399` => `senseshift`.
5. I published the package once again, and now the page for it is broken: https://registry.platformio.org/libraries/senseshift/Serial_BLE
   It is constantly loading, and in Network Devtools bar, there are constant 500 errors.

**Comment by ivankravets** [comment]
Thanks for the report. The issue has been fixed.
