### ISSUE TITLE
Claiming namespace painlessmesh

### ISSUE THREAD

**Issue by BlackEdder** [platformio/platformio-registry#107]
#### Package information

https://registry.platformio.org/libraries/painlessmesh/painlessMesh

#### Description

I am the maintainer of the painlessmesh package (developed here: https://gitlab.com/painlessMesh/painlessMesh). I haven't really had time to work on the package, but wanted to update it now to work on the newer ESP platform. I just released version 1.5.1 and would like to update the version in the platformio registry.

I have a personal account at platformio, but do not seem to have access to the painlessmesh project group.

**Comment by ivankravets** [comment]
It was automatically updated https://registry.platformio.org/libraries/painlessmesh/painlessMesh/versions
