### ISSUE TITLE
Claiming namespace rhaen/TinyLeaf

### ISSUE THREAD

**Issue by rhaen** [platformio/platformio-registry#108]
#### Package information

- Package link: https://registry.platformio.org/libraries/rhaen/TinyLeaf/

#### Description

I am the original author of the package; however accidentally removed the repository and want to reupload a new version with updated code.

**Comment by ivankravets** [comment]
Please login with a PIO Account using Github. 
```
$ pio home
```
User Icon right corner -> Account -> Github

https://docs.platformio.org/en/latest/core/userguide/account/cmd_login.html

The recent source code https://dl.registry.platformio.org/download/rhaen/library/TinyLeaf/0.0.2/TinyLeaf-0.0.2.tar.gz
