### ISSUE TITLE
Claiming namespace [SerialIO]

### ISSUE THREAD

**Issue by Witty-Wizard** [platformio/platformio-registry#111]
#### Package information

- Repository link: https://github.com/Witty-Wizard/SerialIO
- Package Link: https://registry.platformio.org/libraries/witty-wizard/SerialIO

#### Description

I have created this library you can check this on my github history of the repo I even have it published on the Arduino Library Manager However, PlatformIO library manager does not seam to pull the changes from the arduino library manager

**Comment by ivankravets** [comment]
>  PlatformIO library manager does not seam to pull the changes
Because you publish the latest version manually. Once you do this, the PlatformIO Registry disables automatic updates. So, we reenabled this feature again for that library. https://registry.platformio.org/libraries/witty-wizard/SerialIO

**Comment by Witty-Wizard** [comment]
Ahh, I see.
So from now on if i publish a new release it should update automatically right?

**Comment by ivankravets** [comment]
If you mean [this](https://github.com/Witty-Wizard/SerialIO/releases), then YES. Just do not forget to update `version` field in the manfiest.
