### ISSUE TITLE
Library deletion

### ISSUE THREAD

**Issue by akkoyun** [platformio/platformio-registry#12]
Hi,
I have a library named MAX78630 and want to publish it. But I have similar old libraries in my platform organization. I want to delete these libraries and add new library (name change)

these library want to be delete
* [akkoyun/MAX78630 Polyphase Energy Meter](https://registry.platformio.org/libraries/akkoyun/MAX78630%20Polyphase%20Energy%20Meter)
* [akkoyun/EnergyBoard](https://registry.platformio.org/libraries/akkoyun/EnergyBoard)

**Comment by ivankravets** [comment]
Done, thanks!
