### ISSUE TITLE
Two accounts partially merged?

### ISSUE THREAD

**Issue by todd-herbert** [platformio/platformio-registry#19]
#### Package information

- https://registry.platformio.org/libraries/richard26a/AbsoluteMouse
- https://registry.platformio.org/libraries/richard26a/heltec-eink-modules

#### Description

The above libraries are listed under richard26a, rather than myself.
More confusingly, ```pio access list``` now suggests that I have some level of access to Richard's packages?

![image](https://user-images.githubusercontent.com/24772776/169657730-77ec7178-d09c-4a83-bef9-0f510aa8a1ac.png)

**Comment by ivankravets** [comment]
Thanks for the report! Fixed https://registry.platformio.org/search?q=owner%3Atodd-herbert
