### ISSUE TITLE
Claiming namespace `electricui`

### ISSUE THREAD

**Issue by Scottapotamas** [platformio/platformio-registry#22]
#### Package information

- Package link: https://registry.platformio.org/libraries/electricui/electricui-embedded

#### Description

Intended to create/manage the submission of the library to platformio manually, and as part of our CI process.

When attempting to create the account `electricui` via CLI, I got `Error: User with same username already exists` and then found an entry for the library in the registry already.

I assume platformio scraped the Arduino library registry, and created or protects the listed authors on that package. Assuming nothing further happens, will a `library.json` get picked up by scraping on future tagged releases, improving the listing on this registry? 

Is there a way to tie ownership of `electricui` to my account?

Thanks!

**Comment by ivankravets** [comment]
Thanks for contacting us. The ownership of `electricui` organization has been transferred to the `Scottapotamas` account. Please check with `pio org` command. 

> will a library.json get picked up by scraping on future tagged releases, improving the listing on this registry?

PlatformIO supports both manifests: `library.properties` and `library.json`. If you want manually manage library updates, please use `pio pkg publish` command. Once you publish a new version, PlatformIO Regsitry Crawler will never check your repository for the updates, you will need always to publish new versions manually with `pio pkg publish`. We recommend this way.

The current setting for your library is "auto-crawling". PlatformIO checks library.properties manifest and its `version` field. Once a new version is detected and there is a tag for it, PlatformIO will automatically publish a new version for you.

Happy coding with PlatformIO! 🚀
