### ISSUE TITLE
The registry has two identical M5Unit-Sonic

### ISSUE THREAD

**Issue by TinyuZhao** [platformio/platformio-registry#25]
If you [search](https://registry.platformio.org/search?q=M5Unit-Sonic) for M5Unit-Sonic in the registry, you will get two results and no response when you click on it, other [repositories](https://registry.platformio.org/libraries/m5stack/M5Unit-Sonic) do not have this problem

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/44396641/181694102-d15e67db-8e49-4f00-add3-ece350f4fef2.png">

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/44396641/181694111-66bef5ae-9e56-471c-92fc-b2bb5ac22cc9.png">

**Comment by TinyuZhao** [comment]
I just found another problem, if I use the Github login on Platform IO in VsCode, I get a 404.
The problem is similar to [this one](https://community.platformio.org/t/ide-bug-vscode-login-with-social/28984/2)

https://user-images.githubusercontent.com/44396641/181695537-c951e5aa-bf59-4a69-945f-82ecdb5988ed.mov

PlatformIO IDE Version v2.5.1
PlatformIO Core, version 6.1.4a2
VsCode Version 1.69.2

**Comment by ivankravets** [comment]
Thanks for the report, fixed both issues. See https://community.platformio.org/t/ide-bug-vscode-login-with-social/28984/8
