### ISSUE TITLE
Claiming namespace [esp32m]

### ISSUE THREAD

**Issue by dyarkovoy** [platformio/platformio-registry#26]
#### Package information

- Package link: https://registry.platformio.org/libraries/esp32m/ESP32%20logger

#### Description

My github account registered to platformio is dyarkovoy@gmail.com . I am not sure why I can't publish/remove packages under esp32m namespace, since it is one of the organizations in my github account: https://github.com/esp32m
Can you link esp32m namespace to account dyarkovoy@gmail.com ? I'm happy to provide any proof of ownership for https://github.com/esp32m that you need. Thank you.

**Comment by ivankravets** [comment]
Thanks for contacting us! Done! Please check with `pio orgs`.

**Comment by dyarkovoy** [comment]
Thank you!
