### ISSUE TITLE
Tool patch version bump (seemingly) removed an earlier version

### ISSUE THREAD

**Issue by mcspr** [platformio/platformio-registry#27]
Looking at https://registry.platformio.org/tools/mcspr/toolchain-xtensa
Just noticed that after publishing version 5.100300.220621, I could no longer access the previous 5.100300.211127

Is there some kind of file retention policy in place, where older version gets removed after a certain time?
Or, was it an error on my part of some kind while uploading / publishing the package as a version update?
iirc what I have done is `pio pkg pack`'ed some of [esp-quick-toolchain](https://github.com/earlephilhower/esp-quick-toolchain) toolchain archives, and `pkg publish <archive>`'ed results individually.

(pre-emptive sorry if this is not the right place to report issues; not really sure whether this is a bug or not)

**Comment by ivankravets** [comment]
We clean up community packages (tools) with PATCH versions that are not used for a long period. Typically, when a new PATH version of a package is published, the `~5.100300.220621`, means installing the latest version. In your case, it is `5.100300.211127`. This is the rule of https://semver.org/

We do this to save disk space on our mirroring server for community packages.

**Comment by ivankravets** [comment]
Please reopen if you still need help
