### ISSUE TITLE
Claiming viralinkio/ViraLink-MQTT-Client

### ISSUE THREAD

**Issue by armp30** [platformio/platformio-registry#3]
#### Package information

- Package link: https://registry.platformio.org/libraries/viralinkio/ViraLink-MQTT-Client

#### Description

We are maintaining this package under the [viralinkio](https://github.com/viralinkio) organization on github.

**Comment by ivankravets** [comment]
Do you have any issues with access to this package?

**Comment by armp30** [comment]
the release versions are automatic and i dont have any control on it

**Comment by ivankravets** [comment]
Please login to the PlatformIO using Github. See https://docs.platformio.org/en/latest/plus/pio-account.html 

Please inform me when you created `armp30` account on PlatformIO. We will make you an owner of `viralinkio` org.

**Comment by armp30** [comment]
i created armp30 account

**Comment by armp30** [comment]
is automatic deployment based on version number change on library.json file?

**Comment by armp30** [comment]
@valeros

**Comment by armp30** [comment]
@ivankravets

**Comment by ivankravets** [comment]
You are the owner of https://registry.platformio.org/search?q=owner%3Aviralinkio now. Please use `pio package publish --owner viralinkio` next time.
