### ISSUE TITLE
Unable to remove package

### ISSUE THREAD

**Issue by dyarkovoy** [platformio/platformio-registry#30]
`pio pkg unpublish "dyarkovoy/ESP32 logger@1.0.2"`

returns with

`Error: You can unpublish a package version only in 72 hours since the publish date 2021-02-14 16:20:25`

IMHO, it has been well over 72 hours since 2021-02-14

**Comment by ivankravets** [comment]
and how could we help here?

**Comment by dyarkovoy** [comment]
Please help by letting me know how I can remove my package `dyarkovoy/ESP32 logger@1.0.2`

**Comment by ivankravets** [comment]
Do you plan to publish a new version?

**Comment by dyarkovoy** [comment]
This package was published by mistake, so I need to remove all packages under the `dyarkovoy` namespace. The correct namespace is `esp32m` and the correct package is already published here: https://registry.platformio.org/libraries/esp32m/ESP32%20logger

**Comment by ivankravets** [comment]
Done! Thanks for using PlatformIO!
