### ISSUE TITLE
earlephilhower/framework-arduinopico versions not becoming available

### ISSUE THREAD

**Issue by jesserockz** [platformio/platformio-registry#36]
The arduino-pico framework is being published via automatic CI/CD but the recent versions have not been accepted by the moderation team. Is there a specific reason for this?

> Note: I am not in control of the framework, just a concerned user asking why its not being published.

```
Preparing a package...
Type:     tool
Owner:    earlephilhower
Name:     framework-arduinopico
Version:  1.20602.0
Size:     12.26MB
The package publishing may take some time depending on your Internet connection and the package size.
Publishing...
The package has been accepted for moderation. We will notify you on email when process it.
```

Links:
- https://github.com/earlephilhower/arduino-pico/actions/runs/3322051679/jobs/5490539151#step:7:68
- https://registry.platformio.org/tools/earlephilhower/framework-arduinopico
- https://github.com/earlephilhower/arduino-pico/issues/935

**Comment by ivankravets** [comment]
Thanks for the report, fixed!
