### ISSUE TITLE
moved

### ISSUE THREAD

**Issue by armp30** [platformio/platformio-registry#4]
## Report malware or abuse

Please fill out the form to report malware or abuse in a package to the PlatformIO team.

The PlatformIO team will review the report and act accordingly. In cases where malware or abuse is confirmed, the package will be removed and the namespace will be blocked.

Sensitive information should be sent to contact@platformio.org, included this issue link.

Please note that this report goes to the PlatformIO team for triage, not the package maintainer. To report bugs or vulnerabilities in a package please contact the maintainer directly.

#### Package information

- Package name: viralink/Viralink_Arduino_SDK
- Package version: all of them
- Package link: https://registry.platformio.org/libraries/viralink/Viralink_Arduino_SDK

#### Description of vulnerability

we no longer maintain and develop this package and moved to new one https://registry.platformio.org/libraries/viralinkio/ViraLink-MQTT-Client please remove [this](https://registry.platformio.org/libraries/viralink/Viralink_Arduino_SDK)

**Comment by ivankravets** [comment]
Thanks, the package has been deleted.
