### ISSUE TITLE
Claiming namespace loginov-rocks

### ISSUE THREAD

**Issue by loginov-rocks** [platformio/platformio-registry#42]
#### Package information

- Package link: https://registry.platformio.org/libraries/loginov-rocks/UbxGps

#### Description

I am the creator of the UbxGps library and owner of the repository: https://github.com/loginov-rocks/UbxGps

**Comment by ivankravets** [comment]
I see you already have access. Please re-open if you still need any help.

**Comment by loginov-rocks** [comment]
Oh, you are right @ivankravets , thank you a lot!
