### ISSUE TITLE
Claiming namespace ohaut

### ISSUE THREAD

**Issue by mangelajo** [platformio/platformio-registry#47]
#### Package information

- Package link: https://registry.platformio.org/libraries/ohaut/OHAUTlib

#### Description

Hi, I am the original author of this library, and after a while I came back to update
by adding support to a new board I am working on.

I get to push to mangel_ajo/OHAUTlib but not ohaut/OHAUTlib

I have everything under the github.com/ohaut org, all the commits are mine.

This is probably my fault, I wonder if I created at some point an "ohaut" account in platformio and now I fail to remember credentails, I have tried resetting the password just in case, but I don't get any email.

If I try to push from mangel_ajo to 'ohaut' this is what I get

```
ajo@MBP-Miguel ohaut_lib % pio pkg publish --owner ohaut
Preparing a package...
Type:     library
Owner:    ohaut
Name:     OHAUTlib
Version:  0.2.4
Size:     570B

Warning! A package with the name `OHAUTlib` is already published by the next owners: mangel_ajo

Are you sure you want to publish the library ohaut/OHAUTlib@0.2.4 to the registry?
 [y/N]: y
The package publishing may take some time depending on your Internet connection and the package size.
Publishing...
Error: You do not have permission to publish a package using the ohaut account

```

Help is really appreciated. Thanks for this great project.

**Comment by ivankravets** [comment]
Thanks for contacting us.

1. The `mangel_ajo` account was renamed to `mangelajo`. The same as on Github. You can even login with Github. Please don't forget to re-login. You need to use `mangelajo` and your password.
2. You are the owner of `ohaut` org now. Please repeat `pio pkg publish --owner ohaut`

Does it work now?
