### ISSUE TITLE
Claiming namespace subtixx

### ISSUE THREAD

**Issue by Subtixx** [platformio/platformio-registry#48]
#### Package information

- Package link:https://registry.platformio.org/libraries/subtixx/FauxmoESP

#### Description

It is literally my github username 😆

**Comment by ivankravets** [comment]
Have you tried to login to the PlatformIO Account using Github as a provider?

**Comment by Subtixx** [comment]
You mean in PlatformIO home? I am logged in using GitHub there if you mean that

**Comment by ivankravets** [comment]
You have automatically owned all packages. Please check it via https://docs.platformio.org/en/latest/core/userguide/access/cmd_list.html
