### ISSUE TITLE
Claiming namespace mannypeterson/HeliOS

### ISSUE THREAD

**Issue by MannyPeterson** [platformio/platformio-registry#5]
#### Package information

- Package link: https://registry.platformio.org/libraries/mannypeterson/HeliOS

**Comment by ivankravets** [comment]
Hi @MannyPeterson,

Have you tried to log in to [PlatformIO Account](https://docs.platformio.org/en/latest/plus/pio-account.html) using your Github account?

**Comment by MannyPeterson** [comment]
@ivankravets I have but the verify email step does not seem to work for me, I never receive the verification email and I have checked the spam folder.

Also, the package seems to still only show release 0.2.6 even though I released 0.2.7 a few days ago.

**Comment by ivankravets** [comment]
1. Thanks for the report, it was an issue on our side with the legacy crawler. Everything is OK now https://registry.platformio.org/libraries/mannypeterson/HeliOS
2. "verify email step ", it looks like an associated email me@mannypeterson.com is outdated?

**Comment by MannyPeterson** [comment]
Hi @ivankravets 

Thank you for fixing the crawler. Everything looks good now. 😊

The email address you provided is old but it still works and I didn't get the verification email. I did remove that email address from my GitHub account. I will try again.

❤️🇺🇦

**Comment by MannyPeterson** [comment]
Okay, all good now. I logged in with GitHub. What’s next?

**Comment by ivankravets** [comment]
I think nothing :)
If you prefer manually publish updates for your library, you can now use https://docs.platformio.org/en/latest/core/userguide/package/cmd_publish.html
