### ISSUE TITLE
Claiming namespace eccentricorange/DDBot

### ISSUE THREAD

**Issue by eccentricOrange** [platformio/platformio-registry#55]
#### Package information

- Package link: https://registry.platformio.org/libraries/eccentricorange/DDBot

#### Description

I have published the [source code for this on my GitHub page](https://github.com/eccentricOrange/DDBot) and created the [PR that allowed this to be listed in the Arduino Library Index](https://github.com/arduino/library-registry/pull/2610).

**Comment by ivankravets** [comment]
We have just sent you the confirmation email. Please reset your password and log-in with https://docs.platformio.org/en/latest/core/userguide/account/cmd_login.html

Later, you will be able to publish the new package version using https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_publish.html
