### ISSUE TITLE
Claiming namespace lnbits/Nostr

### ISSUE THREAD

**Issue by blackcoffeexbt** [platformio/platformio-registry#56]
#### Package information

- Package link: https://registry.platformio.org/libraries/lnbits/Nostr

#### Description

I am the lead developer and maintainer of this package.

**Comment by ivankravets** [comment]
Please create a [PlatformIO Account](https://docs.platformio.org/en/latest/core/userguide/account/cmd_register.html) and we will assign you as the owner of the lnbits organization. Thanks.

**Comment by blackcoffeexbt** [comment]
Thanks @ivankravets , I've created an account with the username "blackcoffeexbt"

**Comment by ivankravets** [comment]
Done! Please check `pio org list`.
