### ISSUE TITLE
Unknown library registry update status of `arduino-libraries/ArduinoHttpClient`

### ISSUE THREAD

**Issue by Rotzbua** [platformio/platformio-registry#70]
## Situation

At 17.07.23 a new release [0.5.0](https://github.com/arduino-libraries/ArduinoHttpClient/releases/tag/0.5.0) was published. The website still shows an old release `0.4.0`:

https://registry.platformio.org/libraries/arduino-libraries/ArduinoHttpClient

## Problem

It is unclear why there is no update published in the registry.

## Possible solution

Show last scan date / registry update. Then the user knows if there is a problem or the registry is not updated yet.

## Reference

Create release https://github.com/arduino-libraries/ArduinoHttpClient/issues/138

**Comment by ivankravets** [comment]
Thanks, triggered manually the update. https://registry.platformio.org/libraries/arduino-libraries/ArduinoHttpClient
