### ISSUE TITLE
Semantic versioning value parsing seems flawed and leads to unavailable versions

### ISSUE THREAD

**Issue by eldask** [platformio/platformio-registry#72]
Semantic version label parsing seems incorrect and leads to unavailable library versions via the library manager

Taking for example `tzapu/WiFiManager` https://github.com/tzapu/WiFiManager

Here are the available listed available versions

![image](https://github.com/platformio/platformio-vscode-ide/assets/95845091/cedf7fa6-c588-4905-aa43-ea995af82e43)

and here are all the available version from the repo https://github.com/tzapu/WiFiManager/tags

Trying to change `platformio.ini`'s `lib_deps` parameter from `lib_deps = tzapu/WiFiManager@^0.16.0` to `lib_deps = tzapu/WiFiManager@^v2.0.16-rc.2` exposes the error:

```
Resolving esp07 dependencies...
SemanticVersionError: Invalid simple block '^v2.0.16-rc.2'
```

I have run `v2.0.16-rc.2` through a semver linter and it appears valid. I hope I am not creating an invalid issue and thanks to all of you for a great open source project.

**Comment by ivankravets** [comment]
See available versions https://registry.platformio.org/libraries/tzapu/WiFiManager/versions

**Comment by twriverside** [comment]
I believe it is invalid to prepend a 'v' to the version.  The standard says it is common to create tags like "v1.2.3", but that the semantic version string itself is "1.2.3".

From the FAQ [Is “v1.2.3” a semantic version?](https://semver.org/#is-v123-a-semantic-version):
> No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

The syntax you are using (with the '@') is for specifying a version from PlatformIO's Registry.  If you look at the [Version Requirements](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html#cmd-pkg-install-requirements) section in the docs it looks like they expect the actual semantic version or version range specifier (no 'v').

However, if you wanted to specify a specific git tag to use you can do that, and in this case you would have the 'v' in the URI.  See the [Repository](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html#repository-git-hg-svn) section of the specification.  They provide this example there:
> **Clone "v3.3.0" tag of Git repository:**
> `https://github.com/platformio/platform-espressif32.git#v3.3.0`

But you would normally want to use the PlatformIO Registry format so you can use `'^'` ("compatible with"), version ranges, and other features that let you avoid having to specify exact versions for every dependency (see [this](https://devhints.io/semver)).  Using the git tag loses those benefits.
