### ISSUE TITLE
Claiming namespace gitlab-f-schmidt/Ulm_Weatherballoon

### ISSUE THREAD

**Issue by F-Schmidt99** [platformio/platformio-registry#74]
#### Package information

- Package link: https://registry.platformio.org/libraries/gitlab-f-schmidt/Ulm_Weatherballoon

#### Description

I am the owner of the linked gitlab repo at https://gitlab.com/F-Schmidt/ulm_weatherballoon and currently developing this library.

**Comment by ivankravets** [comment]
Done! https://registry.platformio.org/libraries/f-schmidt/Ulm_Weatherballoon

You can log-in with your GitHub account.
