### ISSUE TITLE
Claiming namespace gitlab-f-schmidt/UULM-MCP23008-CORE

### ISSUE THREAD

**Issue by F-Schmidt99** [platformio/platformio-registry#75]
#### Package information

The package link no longer exists. 

#### Description

! PLEASE DELETE THIS LIBRARY, IT WILL NOT BE UPDATED OR REPUBLISHED !
This was my first ever Arduino library which was unreliable and badly written. Please delete this lib from your list!

**Comment by ivankravets** [comment]
Done!
