### ISSUE TITLE
Claiming namespace gitlab-f-schmidt/UULM-MCP23008

### ISSUE THREAD

**Issue by F-Schmidt99** [platformio/platformio-registry#76]
#### Package information

- Package link: no longer exists

#### Description

! PLEASE DELETE THIS LIBRARY, IT WILL NOT BE UPDATED OR REPUBLISHED !
This was my first ever Arduino library which was unreliable and badly written. Please delete this lib from your list!
This lib worked together with [gitlab-f-schmidt/UULM-MCP23008-CORE](https://registry.platformio.org/libraries/gitlab-f-schmidt/UULM-MCP23008-CORE), which is a library, that also does not exist anymore.

**Comment by ivankravets** [comment]
Done!
