### ISSUE TITLE
Duplicate PubSubClient library found

### ISSUE THREAD

**Issue by goddade** [platformio/platformio-registry#79]
## Report malware or abuse

Please fill out the form to report malware or abuse in a package to the PlatformIO team.

The PlatformIO team will review the report and act accordingly. In cases where malware or abuse is confirmed, the package will be removed and the namespace will be blocked.

Sensitive information should be sent to contact@platformio.org, included this issue link.

Please note that this report goes to the PlatformIO team for triage, not the package maintainer. To report bugs or vulnerabilities in a package please contact the maintainer directly.

#### Package information

- Package name: drk/PubSubClient
- Package version: 2.8
- Package link: https://registry.platformio.org/libraries/drk/PubSubClient

#### Description of vulnerability

Please include any references, screenshots, commits, or code examples that would be useful in reproducing the security issue.

It has a different owner than knolleary/PubSubClient, but the content is the same.

**Comment by ivankravets** [comment]
Thanks, removed!
