### ISSUE TITLE
Claiming namespace marlinfirmware

### ISSUE THREAD

**Issue by thinkyhead** [platformio/platformio-registry#83]
#### Package information

- Package link: https://registry.platformio.org/libraries/marlinfirmware/U8glib-HAL

#### Description

The namespace doesn't seem to be associated with my PIO account ("thinkyhead") so I'm denied when I try to publish updates to packages under that namespace. Is that namespace currently unclaimed?

**Comment by ivankravets** [comment]
Hi Scott,

Thanks for contacting us. You are now the owner of `marlinfirmware` organization. Please don't forget to use `pio pkg publish --owner marlinfirmware` when publishing a new version or package.

Happy holidays!

**Comment by thinkyhead** [comment]
Thank you Ivan. Happy holidays to you, and best wishes for the new year!
