### ISSUE TITLE
Claiming namespace [moba160/Button2]

### ISSUE THREAD

**Issue by LennartHennigs** [platformio/platformio-registry#84]
#### Package information

- Package link:

#### Description

Hello,
I noticed that the user moba160 published an old version (v1.6 - from 3 years ago) of my library here:
https://registry.platformio.org/libraries/moba160/Button2

This is the current version:
https://registry.platformio.org/libraries/lennarthennigs/Button2

Please remove the old one from your registry.
Thx.

**Comment by ivankravets** [comment]
Thanks for the report! The duplicated library has been removed.

**Comment by LennartHennigs** [comment]
Thank you!
