### ISSUE TITLE
Auto fetch mixes up version codes

### ISSUE THREAD

**Issue by ayushsharma82** [platformio/platformio-registry#87]
Hi @ivankravets ,

The registry's auto fetch program has a bug where it uses the latest `push` to repo rather than using releases & tags. Often the version code can jump around due to human-error which can cause the following issue with PIO registry.

You'll see the version code was first pushed by mistake as v4.1.0 to repo but later it was changed to v4.0.4. I hope your team can  fix the fetching script on your end and remove the rogue version.

<img width="940" alt="image" src="https://github.com/platformio/platformio-registry/assets/26592968/a188751b-b7c2-4aec-85da-bcb13fd339cb">

Ref: https://github.com/ayushsharma82/ESP-DASH/issues/208

**Comment by ivankravets** [comment]
To avoid similar issues, please use https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_publish.html

If you need to remove the broken versions, please respond to this ticket with the names/numbers that have to be removed.

**Comment by ayushsharma82** [comment]
@ivankravets  Please remove `v4.1.0` of `ayushsharma82/ESP-DASH`. I'll take note of cmd_publish for next time.

**Comment by ivankravets** [comment]
Fixed in https://registry.platformio.org/libraries/ayushsharma82/ESP-DASH/versions
