### ISSUE TITLE
Incorrect information about the library.

### ISSUE THREAD

**Issue by Sam4uk** [platformio/platformio-registry#88]
![IMG_20240301_084249](https://github.com/platformio/platformio-registry/assets/15850554/a491df90-980c-451e-9ff7-d586dc6c0000)
Nanit Robot is not related to this library. 
Incorrectly processed library properties file.

**Comment by ivankravets** [comment]
Hi,
You previously used Nanit Robot for your personal `sam4uk` account. Nevertheless, the issue has been fixed. 

https://registry.platformio.org/search?q=owner%3Asam4uk
