### ISSUE TITLE
Claiming namespace itkindaworks/ESPHelper

### ISSUE THREAD

**Issue by ItKindaWorks** [platformio/platformio-registry#89]
#### Package information

- Package link: 
- https://registry.platformio.org/libraries/itkindaworks/ESPHelper
- https://github.com/ItKindaWorks/ESPHelper

#### Description

I'm not sure if this is the correct place for this request but I'm the owner of It Kinda Works and the ESPHelper library. I'd like to be able push library updates without waiting for the registry to automatically update once a day. I'm not sure what proof I need to show but this account is obviously the account that owns the library here on Github.

**Comment by ivankravets** [comment]
You need to login to the PlatformIO with your Github account and you will receive the full access to your account. See https://docs.platformio.org/en/latest/plus/pio-account.html

Also, this command to publish new version https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_publish.html
