### ISSUE TITLE
Claiming namespace olliiiver

### ISSUE THREAD

**Issue by olliiiver** [platformio/platformio-registry#9]
#### Package information

- Package link: https://registry.platformio.org/libraries/olliiiver/tinyPNG

#### Description

I would like to update my library, but I'm not able to login. 

Seems I have used a mail address that I cannot access anymore. 

It would be very helpful if I could connect my pio account with GitHub.

**Comment by ivankravets** [comment]
Please contact us via [contact@piolabs.com](mailto:contact@piolabs.com) and provide us with an e-mail that you use for Github. You will be able to log in to PlatformIO with Github.

P.S: The library has been updated automatically by our crawler https://registry.platformio.org/libraries/olliiiver/tinyPNG
