### ISSUE TITLE
Old versions have disappeared

### ISSUE THREAD

**Issue by nomis** [platformio/platformio-registry#90]
All of the older versions of my libraries have disappeared, leaving only the latest version:
* https://registry.platformio.org/libraries/nomis/uuid-common/versions
* https://registry.platformio.org/libraries/nomis/uuid-log/versions
* https://registry.platformio.org/libraries/nomis/uuid-console/versions
* https://registry.platformio.org/libraries/nomis/uuid-syslog/versions
* https://registry.platformio.org/libraries/nomis/uuid-telnet/versions
* https://registry.platformio.org/libraries/nomis/uuid-modbus/versions

This breaks all builds that happen to be using a previous version, and any attempts to build with an earlier version for debugging/bug fixing. What's the point of semantic versioning if you're going to unpublish all the older versions and break everything?

```
Library Manager: Installing nomis/uuid-log @ ^2.2.0
Error: Could not find the package with 'nomis/uuid-log @ ^2.2.0' requirements for your system 'linux_x86_64'
```

**Comment by ivankravets** [comment]
Sorry, this a known issue. We have already applied the actions to avoid similar issues in future. 

See https://community.platformio.org/t/missing-packages-in-registry/39076/5

**Comment by nomis** [comment]
You've published a newer version of [tool-scons](https://registry.platformio.org/tools/platformio/tool-scons/versions) yesterday and now the older version has gone missing:
```
Error: Could not find the package with 'platformio/tool-scons @ ~4.40400.0' requirements for your system 'linux_x86_64'
```

**Comment by ivankravets** [comment]
Yes, that was intentionally. What is the reason to use 2-years outdated PlatformIO Core? We just wanted to gather feedback why do people use ancient buggy releases.

**Comment by nomis** [comment]
v6.1.5 is not 2 years old, and [#4531](https://github.com/platformio/platformio-core/issues/4531) hasn't been fixed yet

**Comment by nomis** [comment]
Is this going to be republished or not?

I don't like that you're making all the older versions of my projects impossible to build, especially when they can only be built with older versions of PlatformIO because of all the incompatible changes in v4, v5, v6.

**Comment by nomis** [comment]
I have to use "ancient buggy releases" because the bugs don't affect me and they're the versions that work, whereas newer versions have different incompatibilities.

I can't upgrade because of platformio/platformio-core#4884 which I'm only now aware of because I had to downgrade to v6.1.5 when v6.1.6 came out for platformio/platformio-core#4531.

**Comment by ivankravets** [comment]
> Could not find the package with 'platformio/tool-scons @ ~4.40400.0' 

This version is reverted to the registry. Please re-test your project with the latest PlatformIO Core 6.1.x and report all issues. We work on the PlatormIO Core 7.0 and there will be no support for 6.x soon.
