### ISSUE TITLE
Incorrect owner, repo address, possibly cyber-squatting, please take down ASAP

### ISSUE THREAD

**Issue by tyeth** [platformio/platformio-registry#94]
## Report malware or abuse

Please fill out the form to report malware or abuse in a package to the PlatformIO team.

The PlatformIO team will review the report and act accordingly. In cases where malware or abuse is confirmed, the package will be removed and the namespace will be blocked.

Sensitive information should be sent to contact@platformio.org, included this issue link.

Please note that this report goes to the PlatformIO team for triage, not the package maintainer. To report bugs or vulnerabilities in a package please contact the maintainer directly.

#### Package information

- Package name: nthnn/Adafruit BusIO
- Package version: All
- Package link: https://registry.platformio.org/libraries/nthnn/Adafruit%20BusIO

#### Description of vulnerability

This has probably been accidentally published, but it is taking some of the adafruit BusIO installs, effectively cyber-squatting the library name. There is no listing on the official arduino library registry, and there is no public fork so this is not an "alternative" implementation or anything.

Just seen this warning today, but could have been there for up to 19days (when second library was published)
![image](https://github.com/platformio/platformio-registry/assets/6692083/636500ad-9d97-4e51-aa89-10e0a62576ff)

**Comment by tyeth** [comment]
Just to add this one also looks garbage checking the github link, or maybe the link needs updating:
https://registry.platformio.org/libraries/nthnn/SIM900
https://github.com/nthnn/SIM900

Is there a checking policy to see if the repo exists, the url is not an existing duplicate, and contains a matching library?

**Comment by ivankravets** [comment]
You need to use a valid library declaration as recommended at https://registry.platformio.org/libraries/adafruit/Adafruit%20BusIO/installation

Nevertheless, the duplicated library has been removed.
