### ISSUE TITLE
Claiming namespace [locple]

### ISSUE THREAD

**Issue by locple** [platformio/platformio-registry#99]
#### Package information

- Package link: https://registry.platformio.org/libraries/locple/LiquidCrystal%20I2C%20Multilingual
- Package link: https://registry.platformio.org/libraries/locple/LiquidCrystal_I2C_UTF8

#### Description

I'm the author of these two packages from Arduino Library that were downloaded by PlatformIO automatically.
Now can I claim this namespace in order to update them to newer versions?

Thank you!

Le Phuoc Loc (phuocloc@gmail.com)

**Comment by ivankravets** [comment]
Please verify your email and log-in with `locple` account.

**Comment by locple** [comment]
Thank you very much!
